# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1260, 863)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableView.setFont(font)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setVisible(True)
        self.tableView.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView.horizontalHeader().setMinimumSectionSize(77)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(True)
        self.tableView.verticalHeader().setCascadingSectionResizes(True)
        self.tableView.verticalHeader().setDefaultSectionSize(20)
        self.tableView.verticalHeader().setMinimumSectionSize(20)
        self.tableView.verticalHeader().setSortIndicatorShown(True)
        self.tableView.verticalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 1)
        self.gbox_options_tab1 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbox_options_tab1.sizePolicy().hasHeightForWidth())
        self.gbox_options_tab1.setSizePolicy(sizePolicy)
        self.gbox_options_tab1.setMinimumSize(QtCore.QSize(50, 0))
        self.gbox_options_tab1.setObjectName("gbox_options_tab1")
        self.comboBox = QtWidgets.QComboBox(self.gbox_options_tab1)
        self.comboBox.setGeometry(QtCore.QRect(20, 30, 191, 22))
        self.comboBox.setObjectName("comboBox")
        self.btn_filter = QtWidgets.QPushButton(self.gbox_options_tab1)
        self.btn_filter.setGeometry(QtCore.QRect(20, 80, 93, 28))
        self.btn_filter.setObjectName("btn_filter")
        self.in_filter_class = QtWidgets.QLineEdit(self.gbox_options_tab1)
        self.in_filter_class.setGeometry(QtCore.QRect(140, 80, 311, 22))
        self.in_filter_class.setObjectName("in_filter_class")
        self.gbox_filter = QtWidgets.QGroupBox(self.gbox_options_tab1)
        self.gbox_filter.setGeometry(QtCore.QRect(20, 150, 251, 91))
        self.gbox_filter.setObjectName("gbox_filter")
        self.radio_btn_filter_only = QtWidgets.QRadioButton(self.gbox_filter)
        self.radio_btn_filter_only.setGeometry(QtCore.QRect(20, 30, 211, 20))
        self.radio_btn_filter_only.setChecked(False)
        self.radio_btn_filter_only.setObjectName("radio_btn_filter_only")
        self.radio_btn_filter_include = QtWidgets.QRadioButton(self.gbox_filter)
        self.radio_btn_filter_include.setGeometry(QtCore.QRect(20, 60, 221, 20))
        self.radio_btn_filter_include.setChecked(True)
        self.radio_btn_filter_include.setObjectName("radio_btn_filter_include")
        self.btn_gen_text = QtWidgets.QPushButton(self.gbox_options_tab1)
        self.btn_gen_text.setGeometry(QtCore.QRect(30, 250, 121, 28))
        self.btn_gen_text.setObjectName("btn_gen_text")
        self.lbl_num_objects = QtWidgets.QLabel(self.gbox_options_tab1)
        self.lbl_num_objects.setGeometry(QtCore.QRect(30, 120, 261, 16))
        self.lbl_num_objects.setObjectName("lbl_num_objects")
        self.textBrowser = QtWidgets.QTextBrowser(self.gbox_options_tab1)
        self.textBrowser.setGeometry(QtCore.QRect(20, 350, 521, 281))
        self.textBrowser.setObjectName("textBrowser")
        self.in_text_format = QtWidgets.QLineEdit(self.gbox_options_tab1)
        self.in_text_format.setGeometry(QtCore.QRect(20, 320, 521, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.in_text_format.setFont(font)
        self.in_text_format.setObjectName("in_text_format")
        self.lbl_format = QtWidgets.QLabel(self.gbox_options_tab1)
        self.lbl_format.setGeometry(QtCore.QRect(0, 290, 551, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_format.setFont(font)
        self.lbl_format.setObjectName("lbl_format")
        self.btn_create_dataloader_torch = QtWidgets.QPushButton(self.gbox_options_tab1)
        self.btn_create_dataloader_torch.setGeometry(QtCore.QRect(20, 650, 221, 28))
        self.btn_create_dataloader_torch.setObjectName("btn_create_dataloader_torch")
        self.chck_box_scale_to_1 = QtWidgets.QCheckBox(self.gbox_options_tab1)
        self.chck_box_scale_to_1.setGeometry(QtCore.QRect(430, 240, 81, 20))
        self.chck_box_scale_to_1.setObjectName("chck_box_scale_to_1")
        self.gridLayout.addWidget(self.gbox_options_tab1, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1260, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gbox_options_tab1.setTitle(_translate("MainWindow", "GroupBox"))
        self.btn_filter.setText(_translate("MainWindow", "Filter"))
        self.in_filter_class.setText(_translate("MainWindow", "[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]"))
        self.gbox_filter.setTitle(_translate("MainWindow", "Filter type"))
        self.radio_btn_filter_only.setText(_translate("MainWindow", "Only these objects and others"))
        self.radio_btn_filter_include.setText(_translate("MainWindow", "Include these objects and othres"))
        self.btn_gen_text.setText(_translate("MainWindow", "Genrate text file"))
        self.lbl_num_objects.setText(_translate("MainWindow", "Number of Objects:"))
        self.in_text_format.setText(_translate("MainWindow", "{0:02} {1:03} {2:03} {3:03} {4:03} {5:03} {6:03} {7:03} {8:03} {9} {10}"))
        self.lbl_format.setText(_translate("MainWindow", " [0]class , [1]y_Max  [2]x_Max [3]y_Min [4]x_Min [5]H [6]W[7] x_Center [8]y_Center [9]Diff [10]Name"))
        self.btn_create_dataloader_torch.setText(_translate("MainWindow", "Sava it as Pytorch data Loader"))
        self.chck_box_scale_to_1.setText(_translate("MainWindow", "Scale to 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
